travis: Do not require sudo to install CMake
This commit should fix the error reported below. It turns out that
project enabled in 2015 or later, the default is "sudo: false".

See See https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments


Error:

  [travis:install_cmake.py] Copying /home/travis/downloads/cmake-3.6.2-Linux-x86_64 to /usr/local
  sudo: must be setuid root
  Traceback (most recent call last):
    File "./travis/install_cmake.py", line 86, in <module>
      is_darwin=platform.system().lower() == "darwin")
    File "./travis/install_cmake.py", line 81, in install
      download_dir + "/" + cmake_name + "/", "/usr/local"])
    File "/opt/python/3.4.2/lib/python3.4/subprocess.py", line 561, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['sudo', 'rsync', '-avz', '/home/travis/downloads/cmake-3.6.2-Linux-x86_64/', '/usr/local']' returned non-zero exit status 1