ci/travis/os: Fix failing osx command
It also adds a no-op wrapper script that should be used when command
needs to be quoted before being passed to a wrapper.

This commit fixes the following error:

```
+eval python -c 'import sys;sys.exit(0 if sys.version_info[:3] == (3,4,5) else 1)'
travis/run-with-pyenv.sh: eval: line 8: syntax error near unexpected token `0'
Traceback (most recent call last):
  File "/usr/local/bin/ci", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/ci/__main__.py", line 32, in main
    ci.execute_step(args.step)
  File "/usr/local/lib/python2.7/site-packages/ci/driver.py", line 279, in execute_step
    d.execute_commands(step)
  File "/usr/local/lib/python2.7/site-packages/ci/driver.py", line 266, in execute_commands
    self.check_call(cmd.replace("\\\\", "\\\\\\\\"), env=self.env)
  File "/usr/local/lib/python2.7/site-packages/ci/driver.py", line 78, in check_call
    return subprocess.check_call(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'travis/run-with-pyenv.sh python -c "import sys;sys.exit(0 if sys.version_info[:3] == (3,4,5) else 1)"' returned non-zero
```