test_scikit_ci_addons: Fix "test_path" removing obsolete test case
Since add-on names are now all unique, error like the following can
not be reproduced. This commit removes the test case.

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/path/to/scikit-ci-addons/ci_addons/__init__.py", line 82, in path
      raise SKAddonsError(
  ci_addons.SKAddonsError: Failed to return a single path because it found 2 matching paths. You must select one of these:
    /path/to/scikit-ci-addons/anyci/install_cmake.py
    /path/to/scikit-ci-addons/circle/install_cmake.py